### ISSUE TITLE
Void bug and crash

### ISSUE THREAD

**Issue by timotikun** [LunaPixelStudios/BetterCraft-PLUS#40]
### Describe the Bug

--Explanation--
Bugs and crashes occur in the Void dimension
A strange sound is heard and the game window turns off after 1 or 2 minutes.

--Error Code-- 
The game crashed whilst unexpected error
Error: java.util.ConcurrentModificationException: null
Exit Code: -1

### Reproduction Steps

1. Enderman sounds and all kinds of mobs in the void
2. Sometimes unrelated to the void Sometimes I can hear the sound of Uluru.
3.And if you keep going, the game suddenly stops and shuts down. ( Only when in the Void Dimension )
...

### Screenshots and Videos

![캡처_2022_07_10_01_51_31_917](https://user-images.githubusercontent.com/108998222/178119652-4f03f957-50f6-4ee4-bc21-1c7d95ed39e3.png)

### Crash Report or Log

The game crashed whilst unexpected error Error: java.util.ConcurrentModificationException: null Exit Code: -1

### Operating System

Windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

V39

### Optifine

No

### Other Mods

https://www.curseforge.com/minecraft/mc-mods/undead-expansion
https://www.curseforge.com/minecraft/mc-mods/spiders-2-0
https://www.curseforge.com/minecraft/mc-mods/human-companions
https://www.curseforge.com/minecraft/mc-mods/trolls-community
https://www.curseforge.com/minecraft/mc-mods/mobz
https://www.curseforge.com/minecraft/mc-mods/geode
https://www.curseforge.com/minecraft/mc-mods/rotten-piglins-mod
https://www.curseforge.com/minecraft/mc-mods/good-nights-sleep
https://www.curseforge.com/minecraft/mc-mods/villagers-and-monsters-mod-legency
https://www.curseforge.com/minecraft/mc-mods/pirates-and-looters-mod
https://www.curseforge.com/minecraft/mc-mods/levinide
https://www.curseforge.com/minecraft/mc-mods/dark-caverns
https://www.curseforge.com/minecraft/mc-mods/the-legend-of-herobrine
https://www.curseforge.com/minecraft/mc-mods/queen-bee
https://www.curseforge.com/minecraft/mc-mods/nether-hexed-kingdom
https://www.curseforge.com/minecraft/mc-mods/undead-army
https://www.curseforge.com/minecraft/mc-mods/mobs-genus
https://www.curseforge.com/minecraft/mc-mods/exotic-critters
https://www.curseforge.com/minecraft/mc-mods/the-cursed-realm
https://www.curseforge.com/minecraft/mc-mods/unusual-end
https://www.curseforge.com/minecraft/mc-mods/rediscovered
https://www.curseforge.com/minecraft/mc-mods/illage-and-spillage
https://www.curseforge.com/minecraft/mc-mods/the-end-expansion-mod-4
https://www.curseforge.com/minecraft/mc-mods/elemental-creepers-refabricated
https://www.curseforge.com/minecraft/mc-mods/idolizing
https://www.curseforge.com/minecraft/mc-mods/ravage-and-cabbage
https://www.curseforge.com/minecraft/mc-mods/the-pursuer-herobrine-style-boss-mod

**Comment by SHXRKIIE** [comment]
Too many mods added, not an issue with the modpack
